import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

import "tailwindcss/tailwind.css";
import { Footer } from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " HEXASHOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${inter.className}   text-teal-50`}
      >
        <ThemeProvider>
          <Navbar />
          <div className={` container my-0  min-h-[480px]  flex items-center `}>
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
