import Image from "next/image";
import blog from "public/images/blog.jpg";
import styles from "./page.module.css";
async function getData(id) {
  const res = await fetch(`https://dummyjson.com/products/${id}`);
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export async function generateMetadata({params}){
  const product=await getData(params.id)
  return{
    title:   product.title ,
    description: "Generated by create next app",
  };
}

 
export default async function Post({ params }) {
  const data = await getData(params.id);
  const product = data;
  return (
    <div className=" flex gap-10 justify-center mx-32  flex-col">
      <header className="flex    ">
        <div className={styles.info}>
          <h1 className={styles.title}>{product.title}</h1>
          <p className={styles.desc}>{product.description}</p>
        </div>
        <div className={styles.imgContainer}>
          <Image
            className={styles.postImage}
            src={product.thumbnail}
            sizes="100vw"
            width={300}
            height={300}
            // Make the image display full width
            style={{
              width: "100%",
              height: "100%",
            }}
            alt=""
          />
          <span className={styles.auther}>{product.brand}</span>
        </div>
      </header>
      <div className=" flex justify-center ">
        <div className="grid grid-cols-4 gap-10">
          {product.images.map((image) => (
            <Image
              key={product.id}
              className="   h-[200px] bg-orange-200 hover:border-teal-400 hover:bg-teal-300  border-orange-300 border-2 p-1 rounded-xl "
              src={image}
              width={300}
              height={200}
              // Make the image display full width
              alt=""
            />
          ))}
        </div>
      </div>
    </div>
  );
}
